title = "Playbook"

[[scenes]]
name = "debug"
place = "~/"
actions = [
    "rackup --host=0.0.0.0 --port=9293"
]

[[scenes]]
name = "test"
place = "~/"
actions = [
    "ruby infra/test_http_client.rb -v",
    "ruby infra/test_aliyun_acm_proxy.rb -v",
    "ruby domain/services/test_config_service.rb -v",
    "ruby domain/services/test_encryption_service.rb -v"
]

[[scenes]]
name = "dev"
place = "~/"
actions = [
    "docker stop $(docker ps -a -q --filter name=t2hut-acm)",
    "docker rm $(docker ps -a -q --filter name=t2hut-acm)",
    "docker build --force-rm -t t2hut-acm .",
    "docker run --name t2hut-acm -d -p 9293:9293 -e T2HUT_ACM_ENV=$T2HUT_ACM_ENV -e T2HUT_ACM_ACCESS_KEY=$T2HUT_ACM_ACCESS_KEY -e T2HUT_ACM_SECRET_KEY=$T2HUT_ACM_SECRET_KEY t2hut-acm"
]