title = "Playbook"

[[scenes]]
name = "debug"
place = "~/"
actions = [
    "rackup --host=0.0.0.0 --port=9293"
]

[[scenes]]
name = "test"
place = "~/"
actions = [
    "ruby test_config.rb",
    "ruby infra/test_http_client.rb",
    "ruby infra/test_aliyun_acm_proxy.rb",
    "ruby infra/test_api_result.rb",
    "ruby domain/objects/test_topic.rb",
    "ruby domain/services/test_config_service.rb",
    "ruby domain/services/test_encryption_service.rb",
    "ruby app-services/test_config_app_service.rb"
]

[[scenes]]
name = "dev"
place = "~/"
actions = [
  "docker build --force-rm -t t2hut-acm .",
  "docker stop $(docker ps -a -q --filter name=t2hut-acm)",
  "docker rm $(docker ps -a -q --filter name=t2hut-acm)",
  "docker run --name t2hut-acm -d -p 19293:9293  --network=t2hut_network --ip 172.21.0.3 -e T2HUT_ENV=$T2HUT_ENV -e T2HUT_ACM_ACCESS_KEY=$T2HUT_ACM_ACCESS_KEY -e T2HUT_ACM_SECRET_KEY=$T2HUT_ACM_SECRET_KEY t2hut-acm"
  # "docker run --name t2hut-acm -d -p 19293:9293 -e T2HUT_ENV=$T2HUT_ENV -e T2HUT_ACM_ACCESS_KEY=$T2HUT_ACM_ACCESS_KEY -e T2HUT_ACM_SECRET_KEY=$T2HUT_ACM_SECRET_KEY t2hut-acm"
]

[[scenes]]
name = "log"
place = "~/"
actions = [
    "docker logs -f -t --since=2019-05-17 --tail=100 t2hut-acm"
]