#%RAML 1.0
---
title: 配置
baseUri: https://www.t2hut.com/acm/configs/
version: v1
protocols: [ HTTP, HTTPS ]
mediaType:  application/json
types:
  Config:
    description: 配置
    type: object
    properties:
      identifier: string
        description: 配置的唯一标识UUID，group + | + data_id，base64编码后的结果
        example: VDJIVVR8Y2lwaGVyLXQyaHV0LmJvZGxlaWFuLmNhdGFsb2cub3Nz
      data_id: string
        description: 在阿里云ACM里登记的dataId
        example: cipher-t2hut.bodleian.catalog.oss
      group: string
        description: 配置分组
        example: T2HUT
      content: string
        description: 配置的内容
    Error:
      description: 错误
      type: object
      properties:
        code: string
          description: 错误代码
        message: string
          description: 错误信息

/configs:
get:
  description: 查询所有的配置
  responses:
    200:
    body: object
      properties:
      data: object
          description: 响应数据
          properties:
          total_items:  int
            description: 配置资源的总数量
            type: int
          items:  []Config
      example:
      {
        data: 
        {
          total_items: 1,
          items:
          [
            {
              identifier: "VDJIVVR8Y2lwaGVyLXQyaHV0LmJvZGxlaWFuLmNhdGFsb2cub3Nz",
              data_id: "cipher-t2hut.bodleian.catalog.oss",
              group: "T2HUT",
              content: "π=3.14"
            }
          ]
        }
      }
    500:
    400:
    body: object
      properties:
      error: Error
      example:
      {
        error:
        {
          code: "NullValue",
          message: "ConfigId不能为空"
        }
      }

/configs/{configId}: 
get:
  description: 查询指定配置的内容
  responses:
    200:
    body: object
      properties:
      data: Config
        description: 配置
      example:
      {
        data: 
        {
          identifier: "VDJIVVR8Y2lwaGVyLXQyaHV0LmJvZGxlaWFuLmNhdGFsb2cub3Nz",
          data_id: "cipher-t2hut.bodleian.catalog.oss",
          group: "T2HUT",
          content: "π=3.14"
        }
      }
    500:
    400:
    body:
      type: object
      properties:
      error: Error
      example:
      {
        error:
        {
          code: "NullValue",
          message: "ConfigId不能为空"
        }
      }
